---
Resources:
  MyParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/MyApp/MyParameter1'
      Type: 'String'
      Value: 'MyParameterValue'
      Description: 'Description of my parameter'
      Tier: 'Standard'